version: '3.8'
services:
  db:
      image: postgres:13
      container_name: postgres-db
      ports:
        - 5434:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123
        POSTGRES_DB: nest
      networks:
        - freecodecamp
  # dev-db:
  #     image: postgres:13
  #     ports:
  #       - 5434:5432
  #     environment:
  #       POSTGRES_USER: postgres
  #       POSTGRES_PASSWORD: 123
  #       POSTGRES_DB: nest
  #     networks:
  #       - freecodecamp
  # test-db:
  #     image: postgres:13
  #     ports:
  #       - 5435:5432
  #     environment:
  #       POSTGRES_USER: postgres
  #       POSTGRES_PASSWORD: 123
  #       POSTGRES_DB: nest
  #     networks:
  #       - freecodecamp
  app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: nest-docker-postgres
      environment: 
        - PORT=${PORT}
      ports:
        - 3333:3333
      depends_on:
        - db
      volumes:
        - ./:/app
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

networks:
  freecodecamp: